name: "Install Dependencies"
description: "Install Python dependencies"
inputs:
  package:
    description: "Install the project package"
    default: "false"
    required: false
  test:
    description: "Install the project with test extras"
    default: "false"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Install Python dependencies"
      run: "$GITHUB_ACTION_PATH/action.sh"
      shell: "bash"
      env:
        INSTALL_PACKAGE: ${{ inputs.package }}
        INSTALL_TEST: ${{ inputs.test }}
