name: Live Account Tests

on:
  workflow_dispatch:
    inputs:
      test_target:
        description: "Which live test target to run"
        required: true
        default: "media"
        type: choice
        options:
          - media
          - direct
          - timeline
          - user
          - all

env:
  PYTHON_VERSION: "3.13.5"

jobs:
  live-test:
    runs-on: ubuntu-latest
    env:
      TEST_ACCOUNTS_URL: ${{ secrets.TEST_ACCOUNTS_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          requirements: "true"
          test-requirements: "true"

      - name: Run media test
        if: github.event.inputs.test_target == 'media' || github.event.inputs.test_target == 'all'
        run: pytest -sv tests/live/test_media.py::ClientMediaTestCase tests/live/test_comments.py::ClientCommentRepliesLiveTestCase

      - name: Run direct media test
        if: github.event.inputs.test_target == 'direct' || github.event.inputs.test_target == 'all'
        run: pytest -sv tests/live/test_direct.py::ClientDirectMediaLiveTestCase

      - name: Run timeline test
        if: github.event.inputs.test_target == 'timeline' || github.event.inputs.test_target == 'all'
        run: pytest -sv tests/live/test_timeline.py::ClientTimelineLiveTestCase

      - name: Run user test
        if: github.event.inputs.test_target == 'user' || github.event.inputs.test_target == 'all'
        run: pytest -sv tests/live/test_user.py::ClientUserTestCase

      - name: Run follow request live test
        if: github.event.inputs.test_target == 'user' || github.event.inputs.test_target == 'all'
        run: pytest -sv tests/live/test_user.py::ClientFollowRequestLiveTestCase
